#!/usr/bin/env bash

# brew tap heroku/brew && brew install heroku
# heroku login
# heroku container:login

## heroku create

heroku container:push -a shipsy-leave-bot web
heroku container:release -a shipsy-leave-bot web
